### PR TITLE
Add calling script to start ES on boot

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jacobfk20** [comment]
Sorry I missed this.  I don't pay much attention to this repo anymore as I've forked a new one from Retropie's branch.  I know this is irrelevant, but you made the retropie script module to install this repo right?  Could you make one that builds my latest Release-beta branch and my WifiConnect repo? I don't really know shell that well.

**Comment by ghost** [comment]
Sure... I will try my best.

**Comment by ghost** [comment]
All done!
Go check it out: https://gist.github.com/RetroPieNerd/e319fbe347f2da23239e2eefbe93c5a8

**Comment by jacobfk20** [comment]
Thanks!  I'm going to give it a whirl here soon.

**Pull request closed without merging**
